import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { DEFAULT_REFERENCE_MONTH, formatReferenceMonth, normalizeReferenceMonth, referencePeriodViewFromSearch } from "@/lib/referencePeriod";
import { AlertCircle, ArrowDownRight, ArrowUpRight, BookOpen, CalendarX2, CheckCircle2, ClipboardCheck, GraduationCap, Minus, PieChart as PieChartIcon, UsersRound, UserRoundX } from "lucide-react";
import { useMemo, useState } from "react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const monthNow = DEFAULT_REFERENCE_MONTH;
const labels = { notas: "Notas", material: "Material", reuniao: "Reunião", capacitacao: "Capacitação", evento: "Eventos" } as const;
const palettes = ["#00375d", "#00b1e7", "#afca0a", "#e8425c", "#5185a2"];
const currentYear = new Date().getFullYear();
const yearOptions = Array.from({ length: 12 }, (_, index) => String(currentYear + 1 - index));

function formatMonth(value: string) { return formatReferenceMonth(value); }
function formatPeriod(value: string, period: "month" | "year") { return period === "year" ? value.slice(0, 4) : formatMonth(value); }
function MetricCard({ title, value, detail, icon: Icon, accent, comparison, suffix = "", lowerIsBetter = false, neutral = false, comparisonLabel = "mês anterior" }: { title: string; value: string; detail: string; icon: typeof BookOpen; accent: string; comparison: number; suffix?: string; lowerIsBetter?: boolean; neutral?: boolean; comparisonLabel?: string }) {
  const changed = Math.abs(comparison) > 0.005;
  const positive = lowerIsBetter ? comparison < 0 : comparison > 0;
  const IconTrend = !changed ? Minus : comparison > 0 ? ArrowUpRight : ArrowDownRight;
  const tone = !changed ? "stable" : neutral ? "neutral" : positive ? "better" : "worse";
  const label = !changed ? "Sem variação" : `${comparison > 0 ? "+" : "−"}${Math.abs(comparison).toLocaleString("pt-BR", { maximumFractionDigits: 1 })}${suffix} vs. ${comparisonLabel}`;
  return <Card className="metric-card"><CardContent className="p-5"><div className="flex items-start justify-between"><div className={`metric-icon ${accent}`}><Icon size={18} /></div><span className="metric-dot" /></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">{title}</p><p className="mt-2 text-3xl font-semibold tracking-tight text-foreground">{value}</p><p className="mt-2 text-xs text-muted-foreground">{detail}</p><span className={`metric-variation ${tone}`}><IconTrend size={13} />{label}</span></CardContent></Card>;
}
function EmptyChart({ text }: { text: string }) { return <div className="flex h-[250px] flex-col items-center justify-center text-center"><AlertCircle size={20} className="text-muted-foreground/60" /><p className="mt-3 max-w-[210px] text-sm text-muted-foreground">{text}</p></div>; }

export default function Home() {
  const { user } = useAuth();
  const [month, setMonth] = useState(monthNow);
  const [period, setPeriod] = useState<"month" | "year">(() => referencePeriodViewFromSearch(window.location.search));
  const [segmentId, setSegmentId] = useState("all");
  const [teacherId, setTeacherId] = useState("all");
  const [pendingCategory, setPendingCategory] = useState<keyof typeof labels | null>(null);
  trpc.academic.bootstrap.useQuery();
  const isAdmin = user?.role === "admin";
  const segmentsQuery = trpc.academic.listSegments.useQuery();
  const effectiveSegmentId = isAdmin ? (segmentId === "all" ? undefined : Number(segmentId)) : user?.segmentId ?? undefined;
  const normalizedMonth = normalizeReferenceMonth(month);
  const teacherInput = useMemo(() => effectiveSegmentId ? { segmentId: effectiveSegmentId } : undefined, [effectiveSegmentId]);
  const teachersQuery = trpc.academic.listTeachers.useQuery(teacherInput);
  const summaryInput = useMemo(() => ({ month: normalizedMonth, period, segmentId: effectiveSegmentId, teacherId: teacherId === "all" ? undefined : Number(teacherId) }), [normalizedMonth, period, effectiveSegmentId, teacherId]);
  const summaryQuery = trpc.dashboard.summary.useQuery(summaryInput);
  const pendingInput = useMemo(() => ({ month: normalizedMonth, period, category: pendingCategory ?? "notas", segmentId: effectiveSegmentId, teacherId: teacherId === "all" ? undefined : Number(teacherId) }), [normalizedMonth, period, pendingCategory, effectiveSegmentId, teacherId]);
  const pendenciesQuery = trpc.dashboard.taskPendencies.useQuery(pendingInput, { enabled: pendingCategory !== null });
  const summary = summaryQuery.data;
  const teacher = summary?.teacher;
  const taskEntries = Object.entries(labels) as [keyof typeof labels, string][];

  return <div className="page-shell">
    <header className="page-header"><div><p className="eyebrow">VISÃO ESTRATÉGICA</p><h1>Painel de acompanhamento</h1><p className="page-subtitle">Indicadores de presença e entregas docentes em um só lugar.</p></div><div className="header-chip"><span className="status-pulse" />{isAdmin ? "Visão administrativa" : "Seu segmento"}</div></header>
    <section className="filter-panel"><div className="min-w-[240px]"><p className="filter-label">Período de referência</p><div className="period-selector"><div className="period-mode-toggle" role="group" aria-label="Tipo de período"><button type="button" className={period === "month" ? "active" : ""} onClick={() => setPeriod("month")}>Mensal</button><button type="button" className={period === "year" ? "active" : ""} onClick={() => setPeriod("year")}>Anual</button></div>{period === "month" ? <input aria-label="Mês de referência" type="month" value={normalizedMonth} onChange={event => setMonth(normalizeReferenceMonth(event.target.value))} className="month-input" /> : <Select value={normalizedMonth.slice(0, 4)} onValueChange={year => setMonth(normalizeReferenceMonth(`${year}-01`))}><SelectTrigger aria-label="Ano de referência" className="year-select"><SelectValue /></SelectTrigger><SelectContent>{yearOptions.map(year => <SelectItem key={year} value={year}>{year}</SelectItem>)}</SelectContent></Select>}</div></div><div className="filter-separator" /><div className="min-w-[190px] flex-1"><p className="filter-label">Segmento</p><Select value={isAdmin ? segmentId : String(user?.segmentId || "") } onValueChange={value => { if (isAdmin) { setSegmentId(value); setTeacherId("all"); } }} disabled={!isAdmin || segmentsQuery.isLoading}><SelectTrigger className="border-0 bg-transparent px-0 text-base font-medium shadow-none focus:ring-0"><SelectValue placeholder="Segmento" /></SelectTrigger><SelectContent>{isAdmin && <SelectItem value="all">Todos os segmentos</SelectItem>}{segmentsQuery.data?.map(segment => <SelectItem key={segment.id} value={String(segment.id)}>{segment.name}</SelectItem>)}</SelectContent></Select></div><div className="filter-separator" /><div className="min-w-[220px] flex-1"><p className="filter-label">Professor</p><Select value={teacherId} onValueChange={setTeacherId}><SelectTrigger className="border-0 bg-transparent px-0 text-base font-medium shadow-none focus:ring-0"><SelectValue placeholder="Todos os professores" /></SelectTrigger><SelectContent><SelectItem value="all">Todos os professores</SelectItem>{teachersQuery.data?.filter(item => item.active).map(item => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></div></section>

    {summaryQuery.isLoading ? <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton className="h-[174px] rounded-2xl" key={index} />)}</div> : <>
      <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <MetricCard title="Aulas previstas" value={`${summary?.metrics.totalClasses.toLocaleString("pt-BR", { maximumFractionDigits: 1 }) || 0} h/a`} detail={`Em ${formatPeriod(normalizedMonth, period)}`} icon={BookOpen} accent="sage" comparison={summary?.comparison.totalClasses || 0} suffix=" h/a" neutral comparisonLabel={period === "year" ? "ano anterior" : "mês anterior"} />
        <MetricCard title="Aulas sem professor" value={`${summary?.metrics.uncoveredClasses.toLocaleString("pt-BR", { maximumFractionDigits: 1 }) || 0} h/a`} detail="Carga não ministrada" icon={UserRoundX} accent="terracotta" comparison={summary?.comparison.uncoveredClasses || 0} suffix=" h/a" lowerIsBetter comparisonLabel={period === "year" ? "ano anterior" : "mês anterior"} />
        <MetricCard title="Índice de ausência" value={`${summary?.metrics.uncoveredPercentage.toLocaleString("pt-BR", { maximumFractionDigits: 1 }) || 0}%`} detail="Sobre a carga prevista" icon={CalendarX2} accent="navy" comparison={summary?.comparison.uncoveredPercentage || 0} suffix=" p.p." lowerIsBetter comparisonLabel={period === "year" ? "ano anterior" : "mês anterior"} />
        <MetricCard title="Registros de falta" value={`${summary?.metrics.absences || 0}`} detail="Ocorrências no período" icon={ClipboardCheck} accent="gold" comparison={summary?.comparison.absences || 0} lowerIsBetter comparisonLabel={period === "year" ? "ano anterior" : "mês anterior"} />
      </section>

      {teacher && <section className="teacher-context"><div className="teacher-avatar"><GraduationCap size={22} /></div><div className="min-w-0"><p className="text-sm font-semibold">{teacher.name}</p><p className="text-sm text-muted-foreground">{teacher.discipline} <span className="mx-1 text-border">•</span> {teacher.segmentName}</p></div><div className="teacher-badges">{teacher.assignments.map(item => <Badge key={item.id} variant="secondary">{item.grade} · {item.classGroup}</Badge>)}</div></section>}

          <section className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><Card className="report-card"><CardContent className="p-0"><div className="report-heading"><div><p className="eyebrow">COMPARATIVO</p><h2>Professores com mais faltas</h2><p>Ranking do período selecionado, limitado aos seis maiores registros.</p></div><span className="chart-tag">Top 6</span></div>{summary?.ranking.length ? <div className="h-[280px] px-3 pb-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={summary.ranking} margin={{ top: 22, right: 18, left: -20, bottom: 0 }}><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: "#587487", fontSize: 11 }} interval={0} tickFormatter={value => value.split(" ")[0]} /><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{ fill: "#7c9aae", fontSize: 11 }} /><Tooltip cursor={{ fill: "#e7f8fe" }} contentStyle={{ borderRadius: 12, border: "1px solid #cfe5ef", boxShadow: "0 10px 28px rgba(0,55,93,.12)" }} formatter={(value: number) => [`${value} falta${value === 1 ? "" : "s"}`, "Registros"]} /><Bar dataKey="absences" radius={[7, 7, 2, 2]} fill="#00375d" barSize={34} /></BarChart></ResponsiveContainer></div> : <EmptyChart text="Ainda não há faltas registradas neste período." />}</CardContent></Card>
        <Card className="report-card dark-report"><CardContent className="p-0"><div className="report-heading"><div><p className="eyebrow text-emerald-100/60">QUALIDADE DO REGISTRO</p><h2 className="text-white">Entregas e participação</h2><p className="text-white/60">Acompanhe a consistência dos dados lançados.</p></div><CheckCircle2 className="text-emerald-200" size={24} /></div><div className="quality-list">{taskEntries.map(([category, label], index) => { const stats = summary?.taskStats[category] ?? { yes: 0, no: 0 }; const total = stats.yes + stats.no; const percent = total ? Math.round((stats.yes / total) * 100) : 0; return <div key={category} className="quality-row"><div className="flex items-center gap-3"><span className="quality-number">0{index + 1}</span><span>{label}</span></div><span>{total ? `${percent}% sim` : "Sem registros"}</span></div>; })}</div></CardContent></Card>
      </section>

      <section className="mt-5"><div className="section-heading"><div><p className="eyebrow">CONFORMIDADE DOCENTE</p><h2>Indicadores por categoria</h2></div><p>Clique em um gráfico para listar pendências em {formatPeriod(normalizedMonth, period)}.</p></div><div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-5">{taskEntries.map(([category, label], index) => { const stats = summary?.taskStats[category] ?? { yes: 0, no: 0 }; const total = stats.yes + stats.no; const data = [{ name: "Sim", value: stats.yes }, { name: "Não", value: stats.no }]; return <Card key={category} className="donut-card interactive-donut" role="button" tabIndex={0} aria-label={`Ver pendências de ${label}`} onClick={() => setPendingCategory(category)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") setPendingCategory(category); }}><CardContent className="p-5"><div className="flex items-start justify-between"><p className="font-semibold">{label}</p><PieChartIcon size={16} className="text-muted-foreground" /></div>{total ? <div className="relative mt-3 h-[150px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} cx="50%" cy="50%" innerRadius={45} outerRadius={62} paddingAngle={3} dataKey="value" stroke="none">{data.map((item, pieIndex) => <Cell key={item.name} fill={pieIndex === 0 ? palettes[index] : "#d8e6ed"} />)}</Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-xl font-semibold">{Math.round((stats.yes / total) * 100)}%</span><span className="text-[10px] uppercase tracking-wider text-muted-foreground">sim</span></div></div> : <EmptyChart text="Nenhum lançamento no período." />}<div className="mt-1 flex justify-center gap-4 text-xs text-muted-foreground"><span><i className="legend-dot" style={{ backgroundColor: palettes[index] }} />Sim {stats.yes}</span><span><i className="legend-dot bg-[#d8e6ed]" />Não {stats.no}</span></div><p className="donut-hint"><UsersRound size={13} /> Ver professores pendentes</p></CardContent></Card>; })}</div></section>
    </>}
    <Dialog open={pendingCategory !== null} onOpenChange={open => { if (!open) setPendingCategory(null); }}><DialogContent className="pending-dialog"><DialogHeader><p className="eyebrow">PENDÊNCIAS DO PERÍODO</p><DialogTitle>Professores pendentes — {pendingCategory ? labels[pendingCategory] : ""}</DialogTitle><DialogDescription>Registros marcados como “Não” em {formatPeriod(normalizedMonth, period)}, considerando os filtros ativos no painel.</DialogDescription></DialogHeader>{pendenciesQuery.isLoading ? <div className="space-y-3 py-3">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-16" />)}</div> : pendenciesQuery.data?.length ? <div className="pending-list">{pendenciesQuery.data.map(item => <div className="pending-person" key={item.teacherId}><div className="pending-person-avatar">{item.name.split(" ").slice(0, 2).map(part => part[0]).join("")}</div><div className="min-w-0 flex-1"><p className="font-semibold">{item.name}</p><p className="text-xs text-muted-foreground">{item.discipline} · {item.segmentName}</p><p className="mt-1 text-xs text-muted-foreground">{item.dates.map(date => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(`${date}T12:00:00`))).join(", ")}</p></div><span className="pending-count">{item.pendingCount} {item.pendingCount === 1 ? "pendência" : "pendências"}</span></div>)}</div> : <div className="pending-empty"><UsersRound size={24} /><p>Nenhum professor está pendente nesta categoria.</p></div>}</DialogContent></Dialog>
  </div>;
}
