import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { CircleAlert, Clock3, Plus, Trash2, UserPlus, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

type Assignment = { grade: string; classGroup: string };
type Schedule = { weekday: "segunda" | "terca" | "quarta" | "quinta" | "sexta" | "sabado" | "domingo"; shift: "manha" | "tarde" | "noite"; classHours: string };
const weekdays: { value: Schedule["weekday"]; label: string }[] = [{ value: "segunda", label: "Segunda" }, { value: "terca", label: "Terça" }, { value: "quarta", label: "Quarta" }, { value: "quinta", label: "Quinta" }, { value: "sexta", label: "Sexta" }, { value: "sabado", label: "Sábado" }];
const shifts: { value: Schedule["shift"]; label: string }[] = [{ value: "manha", label: "Manhã" }, { value: "tarde", label: "Tarde" }, { value: "noite", label: "Noite" }];
const initialSchedule: Schedule = { weekday: "segunda", shift: "manha", classHours: "" };

export default function TeacherManagement() {
  const { user } = useAuth();
  const [name, setName] = useState(""); const [discipline, setDiscipline] = useState(""); const [segmentId, setSegmentId] = useState("");
  const [assignments, setAssignments] = useState<Assignment[]>([{ grade: "", classGroup: "" }]); const [schedules, setSchedules] = useState<Schedule[]>([{ ...initialSchedule }]);
  const segmentsQuery = trpc.academic.listSegments.useQuery(); const teachersQuery = trpc.academic.listTeachers.useQuery({ includeInactive: true }); const utils = trpc.useUtils();
  const create = trpc.academic.createTeacher.useMutation({ onSuccess: () => { toast.success("Professor cadastrado com sucesso."); setName(""); setDiscipline(""); setSegmentId(""); setAssignments([{ grade: "", classGroup: "" }]); setSchedules([{ ...initialSchedule }]); utils.academic.listTeachers.invalidate(); }, onError: error => toast.error(error.message) });
  const updateDismissed = trpc.academic.setTeacherDismissed.useMutation({ onSuccess: data => { toast.success(data.dismissed ? "Professor marcado como demitido e removido dos indicadores." : "Professor reativado nos indicadores."); utils.academic.listTeachers.invalidate(); utils.dashboard.summary.invalidate(); utils.dashboard.taskPendencies.invalidate(); utils.academic.listAbsences.invalidate(); utils.academic.listTasks.invalidate(); }, onError: error => toast.error(error.message) });
  if (user?.role !== "admin") return <div className="access-denied"><CircleAlert size={26} /><h1>Acesso restrito</h1><p>O cadastro de professores é exclusivo da administração escolar.</p></div>;
  const addAssignment = () => setAssignments(items => [...items, { grade: "", classGroup: "" }]);
  const updateAssignment = (index: number, field: keyof Assignment, value: string) => setAssignments(items => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const addSchedule = () => setSchedules(items => [...items, { ...initialSchedule }]);
  const updateSchedule = <K extends keyof Schedule>(index: number, field: K, value: Schedule[K]) => setSchedules(items => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const submit = (event: FormEvent) => { event.preventDefault(); const normalizedAssignments = assignments.filter(item => item.grade.trim() && item.classGroup.trim()); const normalizedSchedules = schedules.filter(item => Number(item.classHours) > 0).map(item => ({ ...item, classHours: Number(item.classHours) })); if (!segmentId || !normalizedAssignments.length || !normalizedSchedules.length) return toast.error("Informe segmento, ao menos uma turma e um horário válido."); if (new Set(normalizedSchedules.map(item => `${item.weekday}-${item.shift}`)).size !== normalizedSchedules.length) return toast.error("Não repita o mesmo dia e turno na carga horária."); create.mutate({ name, discipline, segmentId: Number(segmentId), assignments: normalizedAssignments, schedules: normalizedSchedules }); };
  return <div className="page-shell"><header className="page-header"><div><p className="eyebrow">CONFIGURAÇÃO ACADÊMICA</p><h1>Professores e horários</h1><p className="page-subtitle">Cadastre a atuação docente e a carga que sustenta os indicadores de presença.</p></div></header>
    <Card className="form-card mt-7"><CardHeader><div className="module-icon navy"><UserPlus size={18} /></div><CardTitle>Novo professor</CardTitle><p className="card-description">A carga horária por dia e turno é obrigatória para o cálculo das faltas.</p></CardHeader><CardContent><form onSubmit={submit} className="space-y-7"><div className="grid gap-4 md:grid-cols-3"><div className="form-field"><Label htmlFor="teacher-name">Nome completo</Label><Input id="teacher-name" value={name} onChange={event => setName(event.target.value)} placeholder="Ex.: Ana Martins" required /></div><div className="form-field"><Label htmlFor="teacher-discipline">Disciplina</Label><Input id="teacher-discipline" value={discipline} onChange={event => setDiscipline(event.target.value)} placeholder="Ex.: Matemática" required /></div><div className="form-field"><Label>Segmento</Label><Select value={segmentId} onValueChange={setSegmentId}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{segmentsQuery.data?.map(segment => <SelectItem value={String(segment.id)} key={segment.id}>{segment.name}</SelectItem>)}</SelectContent></Select></div></div>
      <div className="config-section"><div className="config-title"><div><p className="eyebrow">ATUAÇÃO</p><h3>Séries e turmas</h3></div><Button type="button" variant="outline" size="sm" onClick={addAssignment}><Plus size={15} /> Adicionar</Button></div><div className="space-y-3">{assignments.map((assignment, index) => <div className="grid grid-cols-[1fr_1fr_auto] gap-3" key={index}><Input value={assignment.grade} onChange={event => updateAssignment(index, "grade", event.target.value)} placeholder="Série, ex.: 8º ano" /><Input value={assignment.classGroup} onChange={event => updateAssignment(index, "classGroup", event.target.value)} placeholder="Turma, ex.: A" />{assignments.length > 1 && <Button type="button" variant="ghost" size="icon" onClick={() => setAssignments(items => items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={16} /></Button>}</div>)}</div></div>
      <div className="config-section"><div className="config-title"><div><p className="eyebrow">JORNADA SEMANAL</p><h3>Carga horária</h3></div><Button type="button" variant="outline" size="sm" onClick={addSchedule}><Plus size={15} /> Adicionar</Button></div><div className="space-y-3">{schedules.map((schedule, index) => <div className="grid grid-cols-[1fr_1fr_1fr_auto] gap-3" key={index}><Select value={schedule.weekday} onValueChange={value => updateSchedule(index, "weekday", value as Schedule["weekday"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{weekdays.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select><Select value={schedule.shift} onValueChange={value => updateSchedule(index, "shift", value as Schedule["shift"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{shifts.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select><Input type="number" min="0.5" max="12" step="0.5" value={schedule.classHours} onChange={event => updateSchedule(index, "classHours", event.target.value)} placeholder="Horas-aula" />{schedules.length > 1 && <Button type="button" variant="ghost" size="icon" onClick={() => setSchedules(items => items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={16} /></Button>}</div>)}</div></div><button className="submit-button max-w-xs" type="submit" disabled={create.isPending}>{create.isPending ? "Cadastrando..." : <><UserPlus size={17} /> Cadastrar professor</>}</button></form></CardContent></Card>
    <section className="mt-7"><div className="section-heading"><div><p className="eyebrow">CORPO DOCENTE</p><h2>Professores cadastrados</h2></div><span className="count-label">{teachersQuery.data?.length || 0} registros</span></div><div className="grid gap-4 lg:grid-cols-2">{teachersQuery.data?.map(teacher => <Card className="teacher-card" key={teacher.id}><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-lg">{teacher.name}</p><p className="mt-1 text-sm text-muted-foreground">{teacher.discipline} · {teacher.segmentName}</p></div><span className={teacher.active ? "active-chip" : "inactive-chip"}>{teacher.active ? "Ativo" : "Demitido"}</span></div><div className="teacher-card-details"><div><p className="detail-label">Séries e turmas</p><div className="mt-2 flex flex-wrap gap-1.5">{teacher.assignments.map(item => <Badge variant="secondary" key={item.id}>{item.grade} · {item.classGroup}</Badge>)}</div></div><div><p className="detail-label"><Clock3 size={13} /> Horários</p><div className="mt-2 flex flex-wrap gap-1.5">{teacher.schedules.map(item => <Badge variant="outline" key={item.id}>{weekdays.find(day => day.value === item.weekday)?.label} · {shifts.find(shiftItem => shiftItem.value === item.shift)?.label} · {Number(item.classHours)} h/a</Badge>)}</div></div><div className="flex items-center justify-between gap-4 rounded-lg border border-border bg-muted/50 px-3 py-2.5"><div><p className="text-sm font-semibold">Status funcional</p><p className="mt-0.5 text-xs text-muted-foreground">Professores demitidos não entram em filtros e indicadores.</p></div><div className="flex shrink-0 items-center gap-2"><Checkbox id={`dismissed-${teacher.id}`} checked={!teacher.active} disabled={updateDismissed.isPending} className="data-[state=checked]:border-destructive data-[state=checked]:bg-destructive" onCheckedChange={checked => updateDismissed.mutate({ teacherId: teacher.id, dismissed: checked === true })} /><Label htmlFor={`dismissed-${teacher.id}`} className="cursor-pointer text-sm font-semibold text-destructive">Demitido</Label></div></div></div></CardContent></Card>)}</div></section>
  </div>;
}
